// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjBfLxWz9ss7jumkV3Sg7eK7xGs7yJJI',
    appId: '1:714773629524:web:ef22853902e38adc6d3bc1',
    messagingSenderId: '714773629524',
    projectId: 'linkit-c9614',
    authDomain: 'linkit-c9614.firebaseapp.com',
    storageBucket: 'linkit-c9614.appspot.com',
    measurementId: 'G-E4BVEZXSDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlE-bYXyCrz4A3okNbazR-OqQlhBXFA5Y',
    appId: '1:714773629524:android:978543872802593e6d3bc1',
    messagingSenderId: '714773629524',
    projectId: 'linkit-c9614',
    storageBucket: 'linkit-c9614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYp70k2koo58Wl2jRneSS-fHrBZsH9DVQ',
    appId: '1:714773629524:ios:1f6c710e70b36d386d3bc1',
    messagingSenderId: '714773629524',
    projectId: 'linkit-c9614',
    storageBucket: 'linkit-c9614.appspot.com',
    iosClientId: '714773629524-08tjgmej787ku4mu2bd7oacjbvvagljf.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYp70k2koo58Wl2jRneSS-fHrBZsH9DVQ',
    appId: '1:714773629524:ios:1f6c710e70b36d386d3bc1',
    messagingSenderId: '714773629524',
    projectId: 'linkit-c9614',
    storageBucket: 'linkit-c9614.appspot.com',
    iosClientId: '714773629524-08tjgmej787ku4mu2bd7oacjbvvagljf.apps.googleusercontent.com',
    iosBundleId: 'com.example.linkit',
  );
}
